[package]
name = "client"
version = "0.1.0"
<<<<<<< HEAD
edition = "2021"

[dependencies]
bevy = "0.14"
bevy_egui = "0.25"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
shared = { path = "../shared" }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
=======
edition = "2024"

[dependencies]
>>>>>>> origin/main
