[package]
name = "server"
version = "0.1.0"
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> df607ba4828db16e8f21f106df1e1970d7dff721
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
shared = { path = "../shared" }
anyhow = "1.0"
env_logger = "0.11"
fastrand = "2.0"
<<<<<<< HEAD
=======
=======
edition = "2024"

[dependencies]
>>>>>>> origin/main
>>>>>>> df607ba4828db16e8f21f106df1e1970d7dff721
