[package]
name = "shared"
version = "0.1.0"
<<<<<<< HEAD
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
=======
edition = "2024"

[dependencies]
>>>>>>> origin/main
