[package]
name = "shared"
version = "0.1.0"
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> df607ba4828db16e8f21f106df1e1970d7dff721
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
<<<<<<< HEAD
=======
=======
edition = "2024"

[dependencies]
>>>>>>> origin/main
>>>>>>> df607ba4828db16e8f21f106df1e1970d7dff721
